### ISSUE TITLE
RuntimeException: Cable added to position

### ISSUE THREAD

**Issue by bigenergy** [Technici4n/Powah#90]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.19.2
- Forge: 1.19.2-43.2.6
- Powah: 4.0.8 & 4.0.10

#### Issue description:
server crash

#### Steps to reproduce:
no info

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))

https://gist.github.com/bigenergy/caaebd27a46d8022de04c40e487a0fa8

**Comment by FyreDraygg** [comment]
I'm observing this issue too, on a server with a custom modpack
In my case it only occurs when shutting down the server, while it tries to save the chunks.

Minecraft 1.19.2, Forge 43.2.8, Powah 4.0.10
I was previously on Powah 4.0.7 and no issue occurred with that version

After many tests I observed that the issue only occurs if a network of Logic Cables from Integrated Dynamics is present in the same chunk as a network of Powah Energy Cables.
When both are present in the same chunk, the server log gets spammed on attempting to `/stop` with
`java.lang.RuntimeException: Cable added to position BlockPos{x=XXX, y=YYY, z=ZZZ}, but there was already one there?`
where XXX YYY ZZZ are the coordinates of a seemingly random Powah Energy Cable in the chunk.

Relevant extract from server service logs:
https://gist.github.com/FyreDraygg/68afef4db93dd5a2aae7d81f981dc7ad
Note how both Integrated Dynamics and Powah appear in the stack traces

To me it looks like both mods are trying to handle their cable networks and get mixed up, but I don't know enough on a code level to try and debug it myself

**Comment by Technici4n** [comment]
Please see my comment on the linked issue. This is a problem with ID in my opinion.

**Comment by Da-Technomancer** [comment]
I think this issue should be re-opened. Powah! shouldn't be causing hard-crashes in the chunk serialization process without a very good reason, as it messes up too many other mods.

**Comment by Technici4n** [comment]
I'd rather have the other mods fix their code. So I'll consider this a feature.

**Comment by dhasial** [comment]
This bug forces me to just delete and not use any powah cables in my world, otherwise it fails to save chunks, hanging until I kill the process.

**Comment by APeng215** [comment]
I ran into a similar crash on my server (crash report: https://mclo.gs/tx7RVIY) and looked into the source code to understand what was happening. 

I’m not very familiar with Minecraft’s chunk loading or BlockEntity lifecycle, so I discussed this issue with ChatGPT and followed its analysis and suggestions. According to that analysis, the crash seems to occur because CableNet.addCable assumes a (Level, BlockPos) will only ever be added once. In practice, during chunk unload / reload or server restart, a new CableTile instance can exist for the same position while an old instance is still referenced in the static map, which leads to the previousCable != null runtime exception.

Based on ChatGPT’s guidance, I applied a small defensive change that makes addCable tolerant to this situation (allowing a stale entry to be replaced instead of throwing), rebuilt the mod, and replaced the server-side jar.

With this patched jar, the server no longer crashes in my case. However, since both the analysis and the fix were derived from ChatGPT’s suggestions rather than my own deep understanding of the lifecycle, I can’t guarantee that this fully fixes the issue in all edge cases.

Patched jar:
[Powah-4.0.11-hotfix-cablenet.zip](https://github.com/user-attachments/files/24521891/Powah-4.0.11-hotfix-cablenet.zip)
Minecraft version: 1.19.2
Forge version: 43.4.12

**Comment by Technici4n** [comment]
This issue typically occurs when other mods incorrectly trigger chunk loading while chunks are being unloaded, and it would be preferable to fix those mods. Maybe I should write a mod that will detect these cases. 😉
